name: CI
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -yq build-essential cmake docbook-xsl libdbus-glib-1-dev libgtk-3-dev libpcre2-dev libvte-2.91-dev xsltproc

    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
